[[plugins]]
  package = "@netlify/plugin-emails"

NETLIFY_EMAILS_PROVIDER	SendGrid
NETLIFY_EMAILS_PROVIDER_API_KEY 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
NETLIFY_EMAILS_SECRET	a9aaa93a-8132-4d15-9d85-4a82ff88bb79
